name: Runnable (stable)

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.md"

env:
  MINIMUM_FLUTTER_VERSION: '3.22.3'

jobs:
  analyze:
    name: Analyze on ${{ matrix.os }} with ${{ matrix.flutter-version }} Flutter
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        flutter-version: [ min, latest ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: flutter-actions/setup-flutter@v4
        with:
          channel: stable
          version: ${{ matrix.flutter-version == 'min' && env.MINIMUM_FLUTTER_VERSION || 'latest' }}
      - name: Log Dart/Flutter versions
        run: |
          dart --version
          flutter --version
      - name: Prepare dependencies
        run: flutter pub get
      - name: Analyse the repo
        run: flutter analyze .
      - name: Generate docs
        run: |
          dart pub global activate dartdoc
          dart pub global run dartdoc .
